version: "3"

services:
  apache:
    build: ./http
    restart: always
    container_name: "${PROJECT_NAME}_apache"
    volumes:
      - ./http/apache2.conf:/opt/docker/etc/httpd/conf.d/apache2.conf
      # - ./vhosts:/opt/docker/etc/httpd/vhost.common.d
      - ./vhosts/vhosts.conf:/opt/docker/etc/httpd/vhost.conf
      - ${WEBROOT}/ssl:/opt/docker/etc/httpd/ssl
      - ${WEBROOT}:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - WEB_PHP_SOCKET=172.30.0.102:9000
      - WEB_ALIAS_DOMAIN=${DOMAIN}
    ports:  
      - '80:80'
      - '443:443'
    links:
        - php
    networks:
      vpcbr:
        ipv4_address: 172.30.0.101
  database:
    image: mariadb:latest
    container_name: "${PROJECT_NAME}_mariadb"
    restart: always
    hostname: mariadb
    env_file:
      - ../.env
    networks:
      vpcbr:
        ipv4_address: 172.30.0.103

    volumes:
      - "../database:/var/lib/mysql"
      - "../database:/etc/mysql/conf.d"
    ports:
      - "3308:3306"
  php:
    build: ./php
    restart: always
    container_name: "${PROJECT_NAME}_php"
    links:
      - database
      - blackfire
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ${WEBROOT}:/var/www/html
      - ./http/apache2.conf:/etc/apache2/apache2.conf
      - ./http/vhosts.conf:/etc/apache2/sites-available/vhosts.conf
      - ./php/phpinfo.php:/var/www/html/info.php
    networks:
      vpcbr:
        ipv4_address: 172.30.0.102
  memcached:
    image: memcached
    container_name: "${PROJECT_NAME}_memcached"
    restart: always
    ports:
      - "11211:11211"
    networks:
      vpcbr:
        ipv4_address: 172.30.0.105
  memcachedAdmin:
    image: hatamiarash7/memcached-admin:latest
    container_name: "${PROJECT_NAME}_memcachedAdmin"
    env_file:
      - ../.env
    ports:
      - 90:80
    networks:
      vpcbr:
        ipv4_address: 172.30.0.104
  blackfire:
    image: blackfire/blackfire:2
    container_name: "${PROJECT_NAME}_blackfire"
    ports: 
      - "8307:8307"
    env_file:
      - ../.env
    networks:
      vpcbr:
        ipv4_address: 172.30.0.106
  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    hostname: mysql
    container_name: "${PROJECT_NAME}_mysql"
    ports:
      - "3306:3306"
    env_file:
      - ../.env
    networks:
      vpcbr:
        ipv4_address: 172.30.0.108
    volumes:
      - "../data:/var/lib/mysql"
      - "../database/my.conf:/etc/mysql/conf.d/my.conf"
      - "../dump.sql:/tmp/dump.sql"
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

